"""Reports: raw month aggregates plus CSV export.

No presentation here: labels, amount formatting, bar heights and printable
views are the frontend's responsibility.
"""
from __future__ import annotations

import io
import re

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.orm import Session

from ..database import get_db
from ..models import Report
from ..services import finance, insights, pdf, storage
from .auth import AuthDep

router = APIRouter(tags=["reports"], dependencies=[AuthDep])

PERIOD_RE = re.compile(r"^\d{4}-\d{2}$")


def _resolve_period(db: Session, period: str | None) -> str:
    """Use the requested 'YYYY-MM' period or fall back to the active one."""
    return period if period and PERIOD_RE.match(period) else finance.current_period(db)


@router.get("/api/reports")
def get_report(period: str | None = None, db: Session = Depends(get_db)):
    """Month aggregates + deltas vs. previous month, all numeric."""
    return finance.report(db, _resolve_period(db, period))


@router.get("/api/insights")
def get_insights(db: Session = Depends(get_db)):
    """Analysis derived from the data itself: profiled, not assumed.

    Served from cache after the first build — regenerating costs LLM calls, so
    it only happens on POST /api/insights/refresh. `stale` flags newer data.
    """
    return insights.get(db)


@router.post("/api/insights/refresh")
def refresh_insights(db: Session = Depends(get_db)):
    """Rebuild the analysis on demand and replace the cached one."""
    return insights.get(db, refresh=True)


@router.get("/api/insights/status")
def insights_status(db: Session = Depends(get_db)):
    """Cheap staleness probe the frontend polls to announce new data."""
    return insights.status(db)


@router.post("/api/insights/report", status_code=201)
def save_insights_report(db: Session = Depends(get_db)):
    """Freeze the current analysis as a PDF in the report library.

    Screen and document come from the same block list — served from the same
    cache — so what the library keeps is exactly what the screen showed.
    """
    from datetime import datetime

    result = insights.get(db)
    totals = result.get("data", {}).get("totales", {})
    stamp = datetime.now()
    title = f"Análisis de datos · {stamp.strftime('%Y-%m-%d %H:%M')}"
    span = totals.get("rango_fechas")
    subtitle = (f"Datos del {span[0]} al {span[1]} · " if span else "") + (
        f"{totals.get('ordenes', {}).get('n', 0)} órdenes · "
        f"{totals.get('gastos', {}).get('n', 0)} gastos")

    content = pdf.analysis_report(title, subtitle, result["blocks"])
    stored = storage.save(content, f"analisis_{stamp.strftime('%Y%m%d_%H%M%S')}.pdf",
                          subfolder="reports")

    intro = next((b["content"] for b in result["blocks"] if b["type"] == "text"), None)
    saved = Report(title=title, kind="analysis", period=None,
                   spec={"totales": totals}, pdf_url=stored["url"],
                   summary=(intro or "")[:400] or None,
                   created_at=stamp.isoformat(timespec="seconds"))
    db.add(saved)
    db.commit()
    return {"id": saved.id, "title": saved.title, "pdf_url": saved.pdf_url}


@router.get("/api/reports/saved")
def list_saved(limit: int = 50, kind: str | None = None, db: Session = Depends(get_db)):
    """Reports generated by the agent: charts, financial PDFs, invoices, receipts."""
    query = select(Report).order_by(Report.created_at.desc(), Report.id.desc())
    if kind:
        query = query.where(Report.kind == kind)
    items = db.scalars(query.limit(max(1, min(limit, 200)))).all()
    return {
        "items": [{
            "id": report.id, "title": report.title, "kind": report.kind,
            "period": report.period, "summary": report.summary,
            "pdf_url": report.pdf_url, "has_chart": bool(report.svg),
            "created_at": report.created_at,
        } for report in items],
    }


@router.get("/api/reports/saved/{report_id}")
def get_saved(report_id: int, db: Session = Depends(get_db)):
    """Full record, including the inline SVG so the gallery can render it."""
    report = db.get(Report, report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="Reporte no encontrado.")
    return {
        "id": report.id, "title": report.title, "kind": report.kind, "period": report.period,
        "summary": report.summary, "svg": report.svg, "pdf_url": report.pdf_url,
        "spec": report.spec, "created_at": report.created_at,
    }


class ReportPatch(BaseModel):
    title: str


@router.patch("/api/reports/saved/{report_id}")
def rename_saved(report_id: int, body: ReportPatch, db: Session = Depends(get_db)):
    """Rename a saved report; the stored file itself is untouched."""
    report = db.get(Report, report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="Reporte no encontrado.")
    title = body.title.strip()
    if not title:
        raise HTTPException(status_code=400, detail="El nombre no puede quedar vacío.")
    report.title = title[:160]
    db.commit()
    return {"id": report.id, "title": report.title}


@router.delete("/api/reports/saved/{report_id}")
def delete_saved(report_id: int, db: Session = Depends(get_db)):
    report = db.get(Report, report_id)
    if report is None:
        raise HTTPException(status_code=404, detail="Reporte no encontrado.")
    db.delete(report)
    db.commit()
    return {"deleted": report_id}


@router.get("/api/reports/export.csv")
def export_csv(period: str | None = None, db: Session = Depends(get_db)):
    """CSV is a data export, so it stays in the backend."""
    p = _resolve_period(db, period)
    rep = finance.report(db, p)
    buf = io.StringIO()
    buf.write("metric,value\n")
    buf.write(f"period,{rep['period']}\n")
    buf.write(f"revenue_usd,{rep['revenue_usd']}\n")
    buf.write(f"expenses_usd,{rep['expenses_usd']}\n")
    buf.write(f"margin_pct,{rep['margin_pct']}\n")
    buf.write(f"orders,{rep['orders_count']}\n")
    for g in rep["gateways"]:
        buf.write(f"gateway_{g['name']},{g['usd']} USD ({g['pct']}%)\n")
    for c in rep["expense_categories"]:
        buf.write(f"expenses_{c['name']},{c['usd']} USD\n")
    return StreamingResponse(
        iter([buf.getvalue()]), media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="report_{p}.csv"'},
    )
